"""
输出格式化器

负责将指法预测结果转换为各种输出格式 (MIDI, MusicXML, JSON等)
"""

import json
import pretty_midi
from pathlib import Path
from typing import Dict, List, Optional
from loguru import logger
from music21 import stream, note, meter, key, tempo, metadata, pitch, expressions


class OutputFormatter:
    """
    输出格式化器
    
    负责将指法预测结果保存为不同格式
    """
    
    def __init__(self):
        """初始化输出格式化器"""
        pass
    
    def save_as_midi(self, result: Dict, output_path: Path, include_fingering_cc: bool = False) -> str:
        """
        保存为MIDI格式 (标准版本，只包含音符信息)
        
        注意: 标准MIDI格式不能直接存储指法信息。此方法主要保存：
        1. 左右手分离的音符轨道
        2. 可选的CC消息存储指法(实验性)
        
        指法信息建议使用JSON、MusicXML或HTML格式查看。
        
        Args:
            result: 预测结果
            output_path: 输出路径
            include_fingering_cc: 是否使用CC消息包含指法信息
            
        Returns:
            实际保存的文件路径
        """
        output_path = Path(output_path)
        if output_path.suffix.lower() != '.mid':
            output_path = output_path.with_suffix('.mid')
        
        try:
            # 创建新的MIDI对象
            midi_data = pretty_midi.PrettyMIDI()
            
            # 创建两个轨道：右手和左手
            right_hand = pretty_midi.Instrument(program=0, name='Piano Right Hand')
            left_hand = pretty_midi.Instrument(program=0, name='Piano Left Hand')
            
            # 处理指法信息
            for fingering in result['fingerings']:
                # 创建音符
                note = pretty_midi.Note(
                    velocity=int(fingering.get('onset_velocity', 80)),
                    pitch=fingering['midi_number'],
                    start=fingering['onset_time'],
                    end=fingering['offset_time']
                )
                
                # 根据手部分配到不同轨道
                if fingering['hand'] == 'right':
                    right_hand.notes.append(note)
                    
                    # 可选: 使用CC消息存储指法信息
                    if include_fingering_cc:
                        cc = pretty_midi.ControlChange(
                            number=102,  # 自定义CC编号用于指法
                            value=max(0, min(127, fingering['finger'] + 64)),
                            time=fingering['onset_time']
                        )
                        right_hand.control_changes.append(cc)
                        
                else:  # left hand
                    left_hand.notes.append(note)
                    
                    if include_fingering_cc:
                        cc = pretty_midi.ControlChange(
                            number=102,  # 同样的CC编号
                            value=max(0, min(127, abs(fingering['finger']) + 64)),
                            time=fingering['onset_time']
                        )
                        left_hand.control_changes.append(cc)
            
            # 添加轨道到MIDI
            if right_hand.notes:
                midi_data.instruments.append(right_hand)
            if left_hand.notes:
                midi_data.instruments.append(left_hand)
            
            # 添加文件信息 (如果支持)
            try:
                text_event = pretty_midi.TextEvent(
                    text="Generated by XLPro Fingering Prediction System",
                    time=0.0
                )
                midi_data.text_events.append(text_event)
                
                if include_fingering_cc:
                    info_event = pretty_midi.TextEvent(
                        text="Fingering stored in CC102: (value-64)=finger_number",
                        time=0.0
                    )
                    midi_data.text_events.append(info_event)
            except:
                pass  # 如果TextEvent不支持就跳过
            
            # 保存文件
            midi_data.write(str(output_path))
            
            if include_fingering_cc:
                logger.info(f"MIDI文件已保存(含指法CC): {output_path}")
            else:
                logger.info(f"MIDI文件已保存(纯音符): {output_path}")
            return str(output_path)
            
        except Exception as e:
            raise ValueError(f"保存MIDI文件失败: {e}")
    
    def save_as_musicxml(self, result: Dict, output_path: Path) -> str:
        """
        保存为MusicXML格式 (带指法标记)
        
        Args:
            result: 预测结果
            output_path: 输出路径
            
        Returns:
            实际保存的文件路径
        """
        output_path = Path(output_path)
        if output_path.suffix.lower() not in ['.xml', '.musicxml']:
            output_path = output_path.with_suffix('.musicxml')
        
        try:
            # 创建music21 stream
            score = stream.Score()
            
            # 添加元数据
            score.metadata = metadata.Metadata()
            score.metadata.title = f"Piano Fingering - {Path(result['input_file']).stem}"
            score.metadata.composer = "Generated by XLPro Model"
            
            # 创建左右手声部
            right_part = stream.Part()
            left_part = stream.Part()
            
            # 添加乐器信息
            right_part.insert(0, meter.TimeSignature('4/4'))
            right_part.insert(0, key.KeySignature(0))  # C major
            right_part.insert(0, tempo.TempoIndication(120))
            
            left_part.insert(0, meter.TimeSignature('4/4'))
            left_part.insert(0, key.KeySignature(0))
            
            # 按手部分组音符
            right_notes = []
            left_notes = []
            
            for fingering in result['fingerings']:
                # 创建音符
                music21_note = note.Note(
                    pitch=pitch.Pitch(midi=fingering['midi_number']),
                    quarterLength=fingering['offset_time'] - fingering['onset_time']
                )
                
                # 添加指法标记
                finger_num = abs(fingering['finger'])
                if finger_num > 0:
                    fingering_mark = expressions.Fingering(finger_num)
                    music21_note.expressions.append(fingering_mark)
                
                # 设置时间偏移
                music21_note.offset = fingering['onset_time']
                
                # 分配到对应声部
                if fingering['hand'] == 'right':
                    right_notes.append(music21_note)
                else:
                    left_notes.append(music21_note)
            
            # 添加音符到声部
            for note_obj in right_notes:
                right_part.insert(note_obj.offset, note_obj)
            
            for note_obj in left_notes:
                left_part.insert(note_obj.offset, note_obj)
            
            # 添加声部到乐谱
            if right_notes:
                score.append(right_part)
            if left_notes:
                score.append(left_part)
            
            # 保存文件
            score.write('musicxml', fp=str(output_path))
            
            logger.info(f"MusicXML文件已保存: {output_path}")
            return str(output_path)
            
        except Exception as e:
            raise ValueError(f"保存MusicXML文件失败: {e}")
    
    def save_as_json(self, result: Dict, output_path: Path) -> str:
        """
        保存为JSON格式 (完整的结构化数据)
        
        Args:
            result: 预测结果
            output_path: 输出路径
            
        Returns:
            实际保存的文件路径
        """
        output_path = Path(output_path)
        if output_path.suffix.lower() != '.json':
            output_path = output_path.with_suffix('.json')
        
        try:
            # 准备输出数据
            output_data = {
                'metadata': {
                    'input_file': result['input_file'],
                    'generation_time': str(pd.Timestamp.now()),
                    'model_info': result.get('metadata', {}),
                    'total_notes': len(result['fingerings'])
                },
                'fingerings': result['fingerings'],
                'statistics': self._compute_statistics(result['fingerings'])
            }
            
            # 保存文件
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(output_data, f, indent=2, ensure_ascii=False)
            
            logger.info(f"JSON文件已保存: {output_path}")
            return str(output_path)
            
        except Exception as e:
            raise ValueError(f"保存JSON文件失败: {e}")
    
    def save_as_csv(self, result: Dict, output_path: Path) -> str:
        """
        保存为CSV格式 (表格数据)
        
        Args:
            result: 预测结果
            output_path: 输出路径
            
        Returns:
            实际保存的文件路径
        """
        output_path = Path(output_path)
        if output_path.suffix.lower() != '.csv':
            output_path = output_path.with_suffix('.csv')
        
        try:
            import pandas as pd
            
            # 转换为DataFrame
            df = pd.DataFrame(result['fingerings'])
            
            # 重新排列列的顺序
            column_order = [
                'note_id', 'onset_time', 'offset_time', 'midi_number', 
                'pitch_name', 'hand', 'finger', 'confidence'
            ]
            
            # 只保留存在的列
            available_columns = [col for col in column_order if col in df.columns]
            df = df[available_columns]
            
            # 保存文件
            df.to_csv(output_path, index=False, encoding='utf-8')
            
            logger.info(f"CSV文件已保存: {output_path}")
            return str(output_path)
            
        except Exception as e:
            raise ValueError(f"保存CSV文件失败: {e}")
    
    def _compute_statistics(self, fingerings: List[Dict]) -> Dict:
        """计算指法统计信息"""
        stats = {
            'total_notes': len(fingerings),
            'hand_distribution': {'right': 0, 'left': 0},
            'finger_distribution': {},
            'pitch_range': {'min': float('inf'), 'max': float('-inf')},
            'duration_stats': {'min': float('inf'), 'max': float('-inf'), 'avg': 0}
        }
        
        if not fingerings:
            return stats
        
        durations = []
        
        for fingering in fingerings:
            # 手部分布
            stats['hand_distribution'][fingering['hand']] += 1
            
            # 指法分布
            finger = fingering['finger']
            if finger != 0:
                stats['finger_distribution'][finger] = stats['finger_distribution'].get(finger, 0) + 1
            
            # 音高范围
            midi_num = fingering['midi_number']
            stats['pitch_range']['min'] = min(stats['pitch_range']['min'], midi_num)
            stats['pitch_range']['max'] = max(stats['pitch_range']['max'], midi_num)
            
            # 时长统计
            duration = fingering['offset_time'] - fingering['onset_time']
            durations.append(duration)
            stats['duration_stats']['min'] = min(stats['duration_stats']['min'], duration)
            stats['duration_stats']['max'] = max(stats['duration_stats']['max'], duration)
        
        # 平均时长
        if durations:
            stats['duration_stats']['avg'] = sum(durations) / len(durations)
        
        return stats
    
    def create_visualization_html(self, result: Dict, output_path: Path) -> str:
        """
        创建可视化HTML文件
        
        Args:
            result: 预测结果
            output_path: 输出路径
            
        Returns:
            实际保存的文件路径
        """
        output_path = Path(output_path)
        if output_path.suffix.lower() != '.html':
            output_path = output_path.with_suffix('.html')
        
        try:
            # 生成HTML内容
            html_content = self._generate_html_visualization(result)
            
            # 保存文件
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            logger.info(f"可视化HTML已保存: {output_path}")
            return str(output_path)
            
        except Exception as e:
            raise ValueError(f"生成可视化HTML失败: {e}")
    
    def _generate_html_visualization(self, result: Dict) -> str:
        """生成HTML可视化内容"""
        fingerings = result['fingerings']
        stats = self._compute_statistics(fingerings)
        
        html = f"""
        <!DOCTYPE html>
        <html lang="zh-CN">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>钢琴指法可视化 - {Path(result['input_file']).stem}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                .header {{ background-color: #f0f0f0; padding: 20px; border-radius: 5px; }}
                .stats {{ display: flex; justify-content: space-around; margin: 20px 0; }}
                .stat-box {{ background-color: #e8f4fd; padding: 15px; border-radius: 5px; text-align: center; }}
                .fingering-table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
                .fingering-table th, .fingering-table td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                .fingering-table th {{ background-color: #f2f2f2; }}
                .right-hand {{ background-color: #fff2cc; }}
                .left-hand {{ background-color: #d5e8d4; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>钢琴指法预测结果</h1>
                <p><strong>输入文件:</strong> {result['input_file']}</p>
                <p><strong>总音符数:</strong> {stats['total_notes']}</p>
            </div>
            
            <div class="stats">
                <div class="stat-box">
                    <h3>右手音符</h3>
                    <p>{stats['hand_distribution']['right']}</p>
                </div>
                <div class="stat-box">
                    <h3>左手音符</h3>
                    <p>{stats['hand_distribution']['left']}</p>
                </div>
                <div class="stat-box">
                    <h3>音高范围</h3>
                    <p>{stats['pitch_range']['min']} - {stats['pitch_range']['max']}</p>
                </div>
            </div>
            
            <h2>指法详情</h2>
            <table class="fingering-table">
                <thead>
                    <tr>
                        <th>音符</th>
                        <th>音高</th>
                        <th>时间</th>
                        <th>手部</th>
                        <th>指法</th>
                        <th>置信度</th>
                    </tr>
                </thead>
                <tbody>
        """
        
        for fingering in fingerings[:50]:  # 只显示前50个音符
            hand_class = 'right-hand' if fingering['hand'] == 'right' else 'left-hand'
            finger_display = abs(fingering['finger']) if fingering['finger'] != 0 else '-'
            
            html += f"""
                    <tr class="{hand_class}">
                        <td>{fingering['note_id']}</td>
                        <td>{fingering['pitch_name']} ({fingering['midi_number']})</td>
                        <td>{fingering['onset_time']:.2f}s</td>
                        <td>{fingering['hand']}</td>
                        <td>{finger_display}</td>
                        <td>{fingering.get('confidence', 0):.3f}</td>
                    </tr>
            """
        
        html += """
                </tbody>
            </table>
            
            <div style="margin-top: 20px; color: #666; font-size: 12px;">
                <p>生成时间: """ + str(pd.Timestamp.now()) + """</p>
                <p>由 XLPro Model 生成</p>
            </div>
        </body>
        </html>
        """
        
        return html


# 需要导入pandas用于时间戳
try:
    import pandas as pd
except ImportError:
    import datetime
    class pd:
        class Timestamp:
            @staticmethod
            def now():
                return datetime.datetime.now() 